language: python

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

before_script:
  - pip install docker-compose

script:
  - docker-compose run --rm drfapi sh -c "python app/manage.py wait_for_db && python manage.py test && flake8"
