version: '3.4'

services:
  drfapi:
    image: drfapi
    command: bash -c "gunicorn 'project.wsgi:application' -c './gunicorn.conf.py'"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment: 
      - DB_HOST=db
      - DB_NAME=drfapi
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on: 
      - db
    
  db:
    image: postgres:10-alpine
    environment: 
      - POSTGRES_DB=drfapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - 5432:5432
  
