version: '3.4'

services:
  drfapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env/dev.env
    depends_on:
      - drfapi_db
      - drfapi_migrations
  drfapi_migrations:
    command: python manage.py migrate
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env/dev.env
    depends_on:
      - drfapi_db
  drfapi_lint:
    command: flake8
    build:
      context: .
      dockerfile: ./Dockerfile
    profiles:
      - lint

  drfapi_test:
    command: python manage.py test
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env/dev.env
    profiles:
      - test
    depends_on:
      - drfapi_db

  drfapi_db:
    image: postgres:10-alpine
    env_file:
      - ./.env/dev.env
    ports:
      - 5432:5432
