version: '3.4'

services:
  drfapi:
    image: drfapi:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env/dev.env
    depends_on:
      - drfapi_db
      - drfapi_migrations

  drfapi_migrations:
    command: sh -c "python manage.py wait_for_db && python manage.py migrate"
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env/dev.env
    depends_on:
      - drfapi_db

  drfapi_utils:
    command: sh -c "python manage.py wait_for_db && python manage.py createsuperuser --noinput"
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env/dev.env
    depends_on:
      - drfapi_db
      - drfapi_migrations

  drfapi_lint:
    image: drfapi
    command: flake8
    profiles:
      - lint

  drfapi_test:
    image: drfapi
    command: sh -c "python manage.py wait_for_db && python manage.py test"
    env_file:
      - ./.env/dev.env
    profiles:
      - test
    depends_on:
      - drfapi_db

  drfapi_db:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.env/dev.env
    ports:
      - 5432:5432

volumes:
  db-data:
